### ISSUE TITLE
RuntimeError:The size of tensor a (10224)must match the size of tensor b (5000)at non-singleton dimension 1

### ISSUE THREAD

**Issue by AndSonder** [kaist-dmlab/DualTF#1]
Hi, I just run ECG.sh without change anything. However I meet the following error. 

<img width="1436" alt="image" src="https://github.com/kaist-dmlab/DualTF/assets/55493212/1bfa4ba0-5c21-41c1-bfbd-68c5500dbe59">

Could you help to solve it ?

**Comment by young-eun-nam** [comment]
We apologize for the delay in responding.
For an ECG, there are nine datasets. 
Each dataset has the following shape:
(1833, 2) (1841, 2)
(2439, 2) (1287, 2)
(10863, 2) (3348, 2)
(2610, 2) (1121, 2)
(2011, 2) (1447, 2)
(2943, 2) (2255, 2)
(34735, 2) (9882, 2)
(2373, 2) (2721, 2)
(3152, 2) (1756, 2)

For some datasets, the overall timestamp length is shorter than others. 
In our experiments, we reported the average window length for the entire ECG dataset, so adjusting the nested window length and sequence length to be shorter will eliminate the Runtime error.
