### ISSUE TITLE
Frequency transformer

### ISSUE THREAD

**Issue by Qiantang-net** [kaist-dmlab/DualTF#2]
Hello, may I ask why I can’t find the code related to Fourier transform?

**Comment by young-eun-nam** [comment]
You can check the Fourier transform in 'utils/data_loader.py' 43th line.

**Comment by DarkFT** [comment]
torch_fft_trasnform() in your code, should it be torch_fft_tr**ans**form?

**Comment by young-eun-nam** [comment]
Thanks for the detail. There was a typo. I updated it.
