### ISSUE TITLE
Too much code repetition

### ISSUE THREAD

**Issue by DarkFT** [kaist-dmlab/DualTF#3]
Thank you for your inspiring work. But what's the difference between AnomalyAttention and  FrequencyAttention other than their names? And there is  too much repetition and miscellaneous in the code which is bad for reading.

**Comment by young-eun-nam** [comment]
There is not much difference in the attention mechanism.
As the paper shows in more detail, the most important technique is using the frequency domain via Nested-Sliding windowing (NS-Window).
AnomalyAttention is for temporal anomaly scores, and FrequencyAttention is for frequency anomaly scores. For readability, they are separated in the code.
